{
  "openapi": "3.0.2",
  "info": {
    "title": "New API",
    "version": "1.0.0",
    "description": "NBRB currency rates"
  },
  "servers": [
    {
      "url": "/api",
      "description": ""
    }
  ],
  "paths": {
    "/rates": {
      "summary": "Get all currency rates",
      "servers": [
        {
          "url": "/api",
          "description": ""
        }
      ],
      "get": {
        "servers": [
          {
            "url": "/api",
            "description": ""
          }
        ],
        "tags": [
          "Rate"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RatesResponse"
                },
                "examples": {
                  "SuccessResponse": {
                    "value": {
                      "data": [
                        {
                          "currency": {
                            "currency_abbr": "AUD",
                            "currency_name": "Австралийский доллар",
                            "id": 440
                          },
                          "currency_id": 440,
                          "date": "2024-06-19T00:00:00Z",
                          "id": 1228,
                          "official_rate": 2.108,
                          "scale": 1
                        }
                      ],
                      "success": true
                    }
                  }
                }
              }
            },
            "description": "Success"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "ErrorResponse": {
                    "value": {
                      "error": "Message",
                      "success": false
                    }
                  }
                }
              }
            },
            "description": "Server error"
          }
        },
        "operationId": "currenciesRates",
        "summary": "All currencies"
      }
    },
    "/rates/{date}": {
      "summary": "Get rates from date",
      "servers": [
        {
          "url": "/api",
          "description": "API server"
        }
      ],
      "get": {
        "tags": [
          "Rate"
        ],
        "parameters": [
          {
            "name": "date",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "date"
            },
            "description": "Date in format YYYY-MM-DD"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RatesResponse"
                },
                "examples": {
                  "SuccessResponse": {
                    "value": {
                      "data": [
                        {
                          "currency": {
                            "currency_abbr": "AUD",
                            "currency_name": "Австралийский доллар",
                            "id": 440
                          },
                          "currency_id": 440,
                          "date": "2024-06-19T00:00:00Z",
                          "id": 1228,
                          "official_rate": 2.108,
                          "scale": 1
                        }
                      ],
                      "success": true
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Validation error",
            "content": {
              "application/json": {
                "examples": {
                  "ErrorResponse": {
                    "value": {
                      "error": "Message",
                      "success": false
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "ErrorResponse": {
                    "value": {
                      "error": "Message",
                      "success": false
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "currencyratesByDate",
        "summary": "Get rates from date"
      }
    }
  },
  "components": {
    "schemas": {
      "RatesResponse": {
        "title": "Root Type for RatesResponse",
        "description": "",
        "type": "object",
        "properties": {
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Rate"
            }
          },
          "success": {
            "type": "boolean"
          }
        },
        "example": {
          "data": [
            {
              "currency": {
                "currency_abbr": "AUD",
                "currency_name": "Австралийский доллар",
                "id": 440
              },
              "currency_id": 440,
              "date": "2024-06-19T00:00:00Z",
              "id": 1228,
              "official_rate": 2.108,
              "scale": 1
            }
          ],
          "success": true
        }
      },
      "Rate": {
        "title": "Root Type for Rate",
        "description": "",
        "type": "object",
        "properties": {
          "currency": {
            "$ref": "#/components/schemas/Currency",
            "properties": {
              "currency_abbr": {
                "type": "string"
              },
              "currency_name": {
                "type": "string"
              },
              "id": {
                "format": "int32",
                "type": "integer"
              }
            }
          },
          "currency_id": {
            "format": "int32",
            "type": "integer"
          },
          "date": {
            "format": "date-time",
            "type": "string"
          },
          "id": {
            "format": "int32",
            "type": "integer"
          },
          "official_rate": {
            "format": "double",
            "type": "number"
          },
          "scale": {
            "format": "int32",
            "type": "integer"
          }
        },
        "example": {
          "currency": {
            "currency_abbr": "AUD",
            "currency_name": "Австралийский доллар",
            "id": 440
          },
          "currency_id": 440,
          "date": "2024-06-19T00:00:00Z",
          "id": 1228,
          "official_rate": 2.108,
          "scale": 1
        }
      },
      "Currency": {
        "title": "Root Type for Currency",
        "description": "",
        "type": "object",
        "properties": {
          "currency": {
            "type": "object",
            "properties": {
              "currency_abbr": {
                "type": "string"
              },
              "currency_name": {
                "type": "string"
              },
              "id": {
                "format": "int32",
                "type": "integer"
              }
            }
          }
        },
        "example": {
          "currency": {
            "currency_abbr": "AUD",
            "currency_name": "Австралийский доллар",
            "id": 440
          }
        }
      },
      "ErrorResponse": {
        "title": "Root Type for ErrorResponse",
        "description": "",
        "type": "object",
        "properties": {
          "error": {
            "type": "string"
          },
          "success": {
            "type": "boolean"
          }
        },
        "example": {
          "error": "Message",
          "success": false
        }
      }
    },
    "responses": {
      "RatesSuccess": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/RatesResponse"
            },
            "examples": {
              "SuccessResponse": {
                "value": {
                  "data": [
                    {
                      "currency": {
                        "currency_abbr": "AUD",
                        "currency_name": "Австралийский доллар",
                        "id": 440
                      },
                      "currency_id": 440,
                      "date": "2024-06-19T00:00:00Z",
                      "id": 1228,
                      "official_rate": 2.108,
                      "scale": 1
                    }
                  ],
                  "success": true
                }
              }
            }
          }
        },
        "description": ""
      }
    }
  }
}